#!/usr/bin/env python3
"""Generate gg_toploader.kicad_pro and the two library tables.

  python3 gen_project.py

Writes:
  gg_toploader.kicad_pro   net classes and design rules
  sym-lib-table            registers lib/gg_adapter.kicad_sym
  fp-lib-table             registers lib/gg_adapter.pretty

RUN THIS AFTER gen_board.py, NEVER BEFORE. pcbnew.SaveBoard() rewrites the sibling
.kicad_pro if one exists, replacing the generated net classes with KiCad's stock
defaults — silently, and the board then carries different rules from the ones written
here. verify_rules.py exists to catch that, and the Makefile orders the two steps.

The rules are the released board's own: 0.2 mm track, 0.2 mm clearance, 0.5 mm to the
board edge. They are not tight, and on this board they do not need to be — the only
crowded feature is the 0.54 mm gap between J1's pads, and nothing routes through it.
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))
import geometry as G      # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = "gg_toploader"


def netclass(name, clearance, track, via_d, via_drill):
    return {
        "name": name,
        "clearance": clearance,
        "track_width": track,
        "via_diameter": via_d,
        "via_drill": via_drill,
        "microvia_diameter": 0.3,
        "microvia_drill": 0.1,
        "diff_pair_width": 0.2,
        "diff_pair_gap": 0.25,
        "diff_pair_via_gap": 0.25,
        "wire_width": 6,
        "bus_width": 12,
        "line_style": 0,
        "pcb_color": "rgba(0, 0, 0, 0.000)",
        "schematic_color": "rgba(0, 0, 0, 0.000)",
        "priority": 2147483647,
    }


def build():
    return {
        "board": {
            "design_settings": {
                "defaults": {
                    "board_outline_line_width": 0.1,
                    "copper_line_width": 0.2,
                    "silk_line_width": 0.1,
                    "silk_text_size_h": 1.0,
                    "silk_text_size_v": 1.0,
                    "silk_text_thickness": 0.15,
                },
                "rules": {
                    "min_clearance": G.CLEARANCE,
                    "min_track_width": G.TRACK_W,
                    "min_via_diameter": 0.5,
                    "min_through_hole_diameter": 0.3,
                    "min_hole_clearance": G.HOLE_CLEARANCE,
                    "min_hole_to_hole": 0.25,
                    # 0.5 mm to the edge, and this one is load-bearing on a card-edge
                    # board: the fab bevels the finger end, and a bevel eats up to
                    # 1 mm of the top surface. Copper closer than the rule allows is
                    # copper the mill can reach.
                    "min_copper_edge_clearance": G.EDGE_CLEARANCE,
                    "min_silk_clearance": 0.0,
                    "min_text_height": 0.8,
                    "min_text_thickness": 0.08,
                },
                "track_widths": [0.0, G.TRACK_W],
                "via_dimensions": [
                    {"diameter": 0.0, "drill": 0.0},
                    {"diameter": G.VIA_DIA, "drill": G.VIA_DRILL},
                ],
            }
        },
        # ONE net class. Every conductor here is a signal passing straight through,
        # including the two grounds and the 5 V rail: there is no plane, no load and
        # no current worth widening for — the console's own contacts are the
        # bottleneck, not 0.2 mm of copper 26 mm long.
        "net_settings": {
            "classes": [netclass("Default", G.CLEARANCE, G.TRACK_W,
                                 G.VIA_DIA, G.VIA_DRILL)],
            "netclass_patterns": [],
            "net_colors": None,
            "netclass_assignments": None,
            "meta": {"version": 3},
        },
        "meta": {"filename": f"{PROJECT}.kicad_pro", "version": 3},
    }


SYM_LIB_TABLE = """(sym_lib_table
  (version 7)
  (lib (name "gg_adapter")(type "KiCad")(uri "${KIPRJMOD}/lib/gg_adapter.kicad_sym")(options "")(descr "Generated by gen_symbol.py"))
)
"""

FP_LIB_TABLE = """(fp_lib_table
  (version 7)
  (lib (name "gg_adapter")(type "KiCad")(uri "${KIPRJMOD}/lib/gg_adapter.pretty")(options "")(descr "Generated by gen_footprints.py"))
)
"""


def main():
    path = os.path.join(HERE, f"{PROJECT}.kicad_pro")
    with open(path, "w") as f:
        json.dump(build(), f, indent=2)
    print(f"wrote {path}")
    print(f"  Default: {G.TRACK_W} mm track, {G.CLEARANCE} mm clearance, "
          f"{G.EDGE_CLEARANCE} mm to the board edge")

    for name, text in (("sym-lib-table", SYM_LIB_TABLE),
                       ("fp-lib-table", FP_LIB_TABLE)):
        p = os.path.join(HERE, name)
        with open(p, "w") as f:
            f.write(text)
        print(f"wrote {p}")


if __name__ == "__main__":
    main()
