// GENERATED by mech/gen_params.py from pcb/lib/geometry.py — do not edit.
//
// x: across the board, 0 = board centre
// z: up from the finger tips, 0 = insertion edge

BOARD_T          = 1.2;   // 1.2 mm — cartridge thickness
BOARD_W          = 99.7204;
BOARD_H          = 40.894;

TONGUE_ROOT_Z    = 14.9352;   // shoulders — shell stops here
TONGUE_W         = 93.472;
TONGUE_LEFT_X    = -46.8122;
TONGUE_RIGHT_X   = 46.6598;
TOP_EDGE_Z       = 40.894;   // where the edge connector is fitted

// The two 2.1 mm holes, which are what the enclosure screws through.
MOUNT_D          = 2.1;
MOUNT_POS = [
    [-34.4678, 22.225],   // MOUNT1
    [35.9664, 22.225],   // MOUNT2
];

// The connector pad field: the top edge is where the edge connector clamps on,
// and its bent tails lie along these pads on both faces.
PAD_FIELD_Z0     = 26.4264;   // lower end of the pads
PAD_FIELD_Z1     = 40.4264;   // upper end, 0.4676 mm below the edge
PAD_FIELD_W      = 90.9;

// Board outline, x/z, in KiCad's winding order.
BOARD_OUTLINE = [
    [-46.8122, 0.0],
    [46.6598, 0.0],
    [46.6598, 14.9352],
    [49.8602, 14.9352],
    [49.8602, 34.036],
    [48.26, 34.036],
    [48.26, 40.894],
    [-43.4594, 40.894],
    [-43.4594, 37.9222],
    [-48.3616, 37.9222],
    [-48.3616, 31.3944],
    [-49.8602, 31.3944],
    [-49.8602, 14.9352],
    [-46.8122, 14.9352],
];

