#!/usr/bin/env python3
"""Export the board's geometry to OpenSCAD — mech/board.scad.

  python3 gen_params.py [-o FILE]

The enclosure has to fit a specific board, and every dimension it needs is already
written down in `pcb/lib/geometry.py`: the outline, the two mounting holes, the tongue,
the thickness. Retyping them here would create a second source of truth for the same
numbers, and the failure would be silent — a shell that fits the board you remember.

So it is exported instead. `board.scad` is GENERATED; edit `pcb/lib/geometry.py` and
re-run this. `enclosure.scad` includes it and never hard-codes a board dimension.

COORDINATES ARE NOT KICAD'S. The board stands up in use, so the model works in the
orientation you hold it in:

    x   across the board, ZERO AT THE BOARD'S CENTRE (KiCad has it at ~135 mm)
    y   through the board — the 1.2 mm thickness, zero at mid-plane
    z   UP from the finger tips: z=0 is the insertion edge, +z is away from the console

z is the flipped one and it is the one to watch: KiCad's y grows DOWNWARD toward the
insertion edge, so z = INSERTION_EDGE_Y - kicad_y. A model built without that flip is
upside down and looks perfectly plausible, because the board is nearly symmetrical.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "pcb", "lib"))
import geometry as G      # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(HERE, "board.scad")

CENTRE_X = (G.BODY_LEFT + G.BODY_RIGHT) / 2


def x(v):
    return round(v - CENTRE_X, 4)


def z(v):
    return round(G.INSERTION_EDGE_Y - v, 4)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    # The outline is walked in KiCad order; flipping y reverses the winding, which
    # OpenSCAD does not care about for a simple polygon but a reader will.
    pts = [(x(px), z(py)) for px, py in G.OUTLINE]

    L = []
    a = L.append
    a("// GENERATED by mech/gen_params.py from pcb/lib/geometry.py — do not edit.")
    a("//")
    a("// x: across the board, 0 = board centre")
    a("// z: up from the finger tips, 0 = insertion edge")
    a("")
    a(f"BOARD_T          = {G.BOARD_THICKNESS};   // 1.2 mm — cartridge thickness")
    a(f"BOARD_W          = {round(G.BOARD_W, 4)};")
    a(f"BOARD_H          = {round(G.BOARD_H, 4)};")
    a("")
    a(f"TONGUE_ROOT_Z    = {z(G.TONGUE_ROOT_Y)};   // shoulders — shell stops here")
    a(f"TONGUE_W         = {round(G.TONGUE_W, 4)};")
    a(f"TONGUE_LEFT_X    = {x(G.TONGUE_LEFT)};")
    a(f"TONGUE_RIGHT_X   = {x(G.TONGUE_RIGHT)};")
    a(f"TOP_EDGE_Z       = {z(G.BODY_TOP)};   // where the edge connector is fitted")
    a("")
    a("// The two 2.1 mm holes, which are what the enclosure screws through.")
    a(f"MOUNT_D          = {G.MOUNT_DRILL};")
    a("MOUNT_POS = [")
    for name, hx, hy in G.MOUNT_HOLES:
        a(f"    [{x(hx)}, {z(hy)}],   // {name}")
    a("];")
    a("")
    a("// The connector pad field: the top edge is where the edge connector clamps on,")
    a("// and its bent tails lie along these pads on both faces.")
    a(f"PAD_FIELD_Z0     = {z(G.GG_PAD_BOTTOM)};   // lower end of the pads")
    a(f"PAD_FIELD_Z1     = {z(G.GG_PAD_TOP)};   // upper end, {round(G.GG_TOP_SETBACK,4)} mm below the edge")
    a(f"PAD_FIELD_W      = {round(abs(G.gg_x(1) - G.gg_x(36)) + G.PAD_W, 4)};")
    a("")
    a("// Board outline, x/z, in KiCad's winding order.")
    a("BOARD_OUTLINE = [")
    for px, pz in pts:
        a(f"    [{px}, {pz}],")
    a("];")
    a("")

    with open(args.out, "w") as f:
        f.write("\n".join(L) + "\n")

    print(f"wrote {args.out}")
    print(f"  outline   : {len(pts)} points, {G.BOARD_W:.3f} x {G.BOARD_H:.3f} mm, "
          f"{G.BOARD_THICKNESS} mm thick")
    print(f"  tongue    : {G.TONGUE_W:.3f} mm wide, exposed below z "
          f"{z(G.TONGUE_ROOT_Y)}")
    print(f"  mounts    : {', '.join(f'({x(hx)}, {z(hy)})' for _, hx, hy in G.MOUNT_HOLES)}"
          f"  d{G.MOUNT_DRILL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
